name: Deploy To GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - run: yarn install --immutable
      - name: Replace API Key in .env
        run: |
          sed -i 's/${GOOGLE_API_KEY}/${{ secrets.GOOGLE_API_KEY }}/g' .env
      - name: Build
        run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
